# Generated by Django 3.1.2 on 2020-11-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(choices=[('ALEX', 'Alex Lianardo'), ('IKHWAN', 'Ikhwan Khalid')], default='ALEX', max_length=100),
        ),
    ]
