# Generated by Django 3.1.2 on 2020-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member',
            field=models.CharField(choices=[('NO', 'No One'), ('AL', 'Alex Lianardo'), ('IK', 'Muhammad Ikhwan Khalid')], default='NO', max_length=2),
        ),
    ]
