# Generated by Django 3.1.2 on 2020-11-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='member',
            field=models.CharField(choices=[('No one', 'No One'), ('Alex Lianardo', 'Alex Lianardo'), ('Muhammad Ikhwan Khalid', 'Muhammad Ikhwan Khalid')], max_length=100),
        ),
    ]
